# Generated by Django 4.2 on 2023-04-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=50)),
                ('birthdate', models.CharField(max_length=50)),
                ('gendermale', models.CharField(max_length=50)),
                ('genderfemale', models.CharField(max_length=50)),
                ('gendernone', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=50)),
            ],
        ),
    ]
